# Generated by Django 4.1.5 on 2023-03-14 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_catergory_options_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catergory',
            new_name='Category',
        ),
    ]
